//
//  MyStyleKit.h
//  ProjectName
//
//  Created by AuthorName on 2017/12/20.
//  Copyright © 2017 CompanyName. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import <UIKit/UIKit.h>



typedef enum : NSInteger
{
    MyStyleKitResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    MyStyleKitResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    MyStyleKitResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    MyStyleKitResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.

} MyStyleKitResizingBehavior;

extern CGRect MyStyleKitResizingBehaviorApply(MyStyleKitResizingBehavior behavior, CGRect rect, CGRect target);


@interface MyStyleKit : NSObject

// Colors
+ (UIColor*)bubbleColor;

// Drawing Methods
+ (void)drawBubbleButtonWithFrame: (CGRect)frame title: (NSString*)title pressed: (BOOL)pressed;
+ (void)drawChatIconWithIconColor: (UIColor*)iconColor scale: (CGFloat)scale;
+ (void)drawChatIconWithFrame: (CGRect)targetFrame resizing: (MyStyleKitResizingBehavior)resizing iconColor: (UIColor*)iconColor scale: (CGFloat)scale;
+ (void)drawPaperPlaneIcon;
+ (void)drawCanvas1WithIconColor: (UIColor*)iconColor;

@end
